# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片路径')),
                ('name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('datetime', models.DateTimeField(verbose_name='图片日期')),
                ('source', models.CharField(max_length=255, verbose_name='图片来源')),
            ],
            options={
                'db_table': 'yiban_nav',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片路径')),
                ('name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('datetime', models.DateTimeField(verbose_name='图片日期')),
                ('source', models.CharField(max_length=255, verbose_name='图片来源')),
            ],
            options={
                'db_table': 'yiban_wheel',
            },
        ),
        migrations.CreateModel(
            name='YibanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片路径')),
                ('name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('datetime', models.DateTimeField(verbose_name='图片日期')),
                ('source', models.CharField(max_length=255, verbose_name='图片来源')),
                ('skudict', models.CharField(max_length=255, verbose_name='sku')),
                ('category', models.CharField(max_length=255, verbose_name='类目树')),
                ('productimg', models.CharField(max_length=255, verbose_name='商品图片集')),
                ('shortname', models.CharField(max_length=15, verbose_name='短名称')),
                ('longname', models.CharField(max_length=60, verbose_name='长名称')),
                ('brandname', models.CharField(default=None, max_length=255, verbose_name='品牌名称')),
                ('brandlogo', models.CharField(default=None, max_length=255, verbose_name='品牌logo')),
                ('uploaddate', models.DateTimeField(verbose_name='上传日期')),
                ('props', models.CharField(max_length=255, verbose_name='商品属性表')),
            ],
            options={
                'db_table': 'yiban_product',
            },
        ),
        migrations.CreateModel(
            name='YibanShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=255, verbose_name='店铺名称')),
            ],
            options={
                'db_table': 'yiban_shop',
            },
        ),
        migrations.CreateModel(
            name='YibanSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuprops', models.CharField(max_length=255, verbose_name='sku属性')),
                ('primaryprice', models.IntegerField(verbose_name='原价')),
                ('discountprice', models.IntegerField(verbose_name='折扣价')),
                ('inventory', models.IntegerField(verbose_name='库存')),
                ('sales', models.IntegerField(verbose_name='销量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='home.YibanProduct')),
            ],
            options={
                'db_table': 'yiban_sku',
            },
        ),
        migrations.AddField(
            model_name='yibanproduct',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.YibanShop'),
        ),
    ]
