# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_yibanproduct_mainprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yibanproduct',
            name='mainprice',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=9, verbose_name='商品主价格'),
        ),
    ]
