# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191225_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yibanproduct',
            name='brandlogo',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='brandname',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='productimg',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='props',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='shortname',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='skudict',
        ),
        migrations.RemoveField(
            model_name='yibanproduct',
            name='uploaddate',
        ),
        migrations.AlterField(
            model_name='nav',
            name='datetime',
            field=models.DateTimeField(default='2019-8-8', verbose_name='图片日期'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='source',
            field=models.CharField(default='/', max_length=255, verbose_name='图片来源'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='datetime',
            field=models.DateTimeField(default='2019-8-8', verbose_name='图片日期'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='source',
            field=models.CharField(default='/', max_length=255, verbose_name='图片来源'),
        ),
        migrations.AlterField(
            model_name='yibanproduct',
            name='datetime',
            field=models.DateTimeField(default='2019-8-8', verbose_name='图片日期'),
        ),
        migrations.AlterField(
            model_name='yibanproduct',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='yibanproduct',
            name='source',
            field=models.CharField(default='/', max_length=255, verbose_name='图片来源'),
        ),
    ]
