# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191225_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='yibanproduct',
            name='brandname',
            field=models.CharField(default=None, max_length=255, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='yibanproduct',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.YibanShop'),
        ),
    ]
