# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-25 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_yibankidsrenproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YibanKidsrenProduct',
            new_name='YibanKidsProduct',
        ),
    ]
