# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-26 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_yibandiscountproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='YibanBrandNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片路径')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='图片名称')),
                ('datetime', models.DateTimeField(default='2019-8-8', verbose_name='图片日期')),
                ('source', models.CharField(default='/', max_length=255, verbose_name='图片来源')),
            ],
            options={
                'db_table': 'yiban_brand_nav',
            },
        ),
    ]
