# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_yibanbrandnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='yibandiscountproduct',
            name='productimg',
            field=models.CharField(default='/', max_length=255, verbose_name='商品图片集'),
        ),
        migrations.AddField(
            model_name='yibankidsproduct',
            name='productimg',
            field=models.CharField(default='/', max_length=255, verbose_name='商品图片集'),
        ),
        migrations.AddField(
            model_name='yibanmanproduct',
            name='productimg',
            field=models.CharField(default='/', max_length=255, verbose_name='商品图片集'),
        ),
        migrations.AddField(
            model_name='yibanproduct',
            name='productimg',
            field=models.CharField(default='/', max_length=255, verbose_name='商品图片集'),
        ),
    ]
