# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191226_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yibansku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='home.YibanDiscountProduct'),
        ),
    ]
