# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191226_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='yibandiscountproduct',
            name='skudict',
            field=models.CharField(default='{"color":["red",],"size":["L","M","S"]}', max_length=255, verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='yibankidsproduct',
            name='skudict',
            field=models.CharField(default='{"color":["red",],"size":["L","M","S"]}', max_length=255, verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='yibanmanproduct',
            name='skudict',
            field=models.CharField(default='{"color":["red",],"size":["L","M","S"]}', max_length=255, verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='yibanproduct',
            name='skudict',
            field=models.CharField(default='{"color":["red",],"size":["L","M","S"]}', max_length=255, verbose_name='sku'),
        ),
    ]
