# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191226_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yibansku',
            name='discountprice',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='折扣价'),
        ),
        migrations.AlterField(
            model_name='yibansku',
            name='primaryprice',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='原价'),
        ),
    ]
