# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YibanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='邮箱')),
                ('avatar', models.CharField(max_length=100, verbose_name='头像路径')),
                ('is_active', models.BooleanField(default=False, verbose_name='邮箱是否激活')),
            ],
            options={
                'verbose_name': '买家用户',
                'db_table': 'yiban_user',
            },
        ),
    ]
