# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('order_code', models.CharField(max_length=100, verbose_name='订单编号')),
                ('total_count', models.IntegerField(verbose_name='订单总数量')),
                ('total_amount', models.FloatField(verbose_name='订单总价格')),
                ('status', models.SmallIntegerField(default=1, verbose_name='1未支付,2已支付，未发货')),
            ],
            options={
                'db_table': 'yiban_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('order_code', models.CharField(max_length=100, verbose_name='订单编号')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('counts', models.IntegerField(verbose_name='商品数量')),
                ('price', models.FloatField(verbose_name='商品单价')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
