# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_count',
        ),
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.CharField(default=None, max_length=255, verbose_name='订单详情'),
            preserve_default=False,
        ),
    ]
