# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191228_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=models.CharField(max_length=1000, verbose_name='订单详情'),
        ),
    ]
